export const MAJOR_CITIES = [
  "Agra",
  "Ahmedabad",
  "Amritsar",
  "Austin",
  "Baltimore",
  "Bengaluru",
  "Bhopal",
  "Boston",
  "Charlotte",
  "Chennai",
  "Chicago",
  "Coimbatore",
  "Columbus",
  "Dallas",
  "Delhi",
  "Denver",
  "Detroit",
  "El Paso",
  "Faridabad",
  "Fort Worth",
  "Houston",
  "Hyderabad",
  "Indianapolis",
  "Indore",
  "Jacksonville",
  "Jaipur",
  "Kanpur",
  "Kochi",
  "Kolkata",
  "Las Vegas",
  "Los Angeles",
  "Louisville",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Memphis",
  "Meerut",
  "Milwaukee",
  "Mumbai",
  "Nagpur",
  "Nashik",
  "Nashville",
  "New York",
  "Oklahoma City",
  "Patna",
  "Philadelphia",
  "Phoenix",
  "Portland",
  "Pune",
  "Rajkot",
  "San Antonio",
  "San Diego",
  "San Francisco",
  "San Jose",
  "Seattle",
  "Surat",
  "Thiruvananthapuram",
  "Varanasi",
  "Vadodara",
  "Visakhapatnam",
  "Washington, D.C.",
];
